# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/appExample.xcworkspace -scheme appExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
